import { estimateTokens } from "./tokens.js";
import { redactSecrets, findSecrets, type SecretHit } from "./secrets.js";
import { walkFiles, buildTree, type FileEntry } from "./walk.js";

export type OutputFormat = "markdown" | "xml" | "json";

export interface PackOptions {
  root: string;
  maxTokens?: number;
  format?: OutputFormat;
  extraIgnore?: string[];
  include?: string[];
  redact?: boolean;
  tree?: boolean;
  maxFileBytes?: number;
}

export interface PackedFile {
  path: string;
  tokens: number;
  size: number;
  truncated: boolean;
  content: string;
  kept: boolean;
}

export interface PackResult {
  files: PackedFile[];
  dropped: PackedFile[];
  tree: string;
  tokens: number;
  secrets: Array<SecretHit & { path: string }>;
  redactedCount: number;
  output: string;
}

const PRIORITY_BOOST: Array<{ test: (p: string) => boolean; boost: number }> = [
  { test: (p) => /(^|\/)readme(\.[a-z]+)?$/i.test(p), boost: 8 },
  { test: (p) => /(^|\/)package\.json$/.test(p), boost: 7 },
  { test: (p) => /(^|\/)pyproject\.toml$/.test(p), boost: 7 },
  { test: (p) => /(^|\/)cargo\.toml$/.test(p), boost: 7 },
  { test: (p) => /(^|\/)go\.mod$/.test(p), boost: 7 },
  { test: (p) => p.startsWith("src/") || p.startsWith("lib/"), boost: 5 },
  { test: (p) => /(^|\/)index\.[a-z]+$/.test(p), boost: 4 },
  { test: (p) => /\.(ts|tsx|js|jsx|py|go|rs|java)$/.test(p), boost: 3 },
  { test: (p) => p.startsWith("tests/") || p.startsWith("test/"), boost: 1 },
  { test: (p) => p.startsWith("docs/"), boost: 1 },
];

function score(file: FileEntry): number {
  let s = 0;
  for (const rule of PRIORITY_BOOST) if (rule.test(file.path)) s += rule.boost;
  s -= Math.log10(Math.max(file.size, 10));
  return s;
}

export function pack(options: PackOptions): PackResult {
  const maxTokens = options.maxTokens ?? 80_000;
  const format = options.format ?? "markdown";
  const redact = options.redact ?? true;
  const entries = walkFiles({
    root: options.root,
    extraIgnore: options.extraIgnore,
    include: options.include,
    maxFileBytes: options.maxFileBytes,
  });

  const secrets: Array<SecretHit & { path: string }> = [];
  let redactedCount = 0;
  const ranked = entries
    .map((entry) => {
      const found = findSecrets(entry.content);
      for (const hit of found) secrets.push({ ...hit, path: entry.path });
      let content = entry.content;
      if (redact) {
        const redacted = redactSecrets(content);
        content = redacted.text;
        redactedCount += redacted.count;
      }
      if (entry.truncated) content += "\n\n/* [truncated by ctxpack] */\n";
      return {
        path: entry.path,
        size: entry.size,
        truncated: entry.truncated,
        content,
        tokens: estimateTokens(content),
        kept: false,
        _score: score(entry),
      };
    })
    .sort((a, b) => b._score - a._score);

  const kept: PackedFile[] = [];
  const dropped: PackedFile[] = [];
  let used = 0;
  const treeText = options.tree === false ? "" : buildTree(ranked.map((f) => f.path));
  const treeTokens = treeText ? estimateTokens(treeText) + 40 : 0;
  used += treeTokens;

  for (const file of ranked) {
    const { _score, ...rest } = file;
    void _score;
    if (used + rest.tokens > maxTokens) {
      dropped.push({ ...rest, kept: false });
      continue;
    }
    kept.push({ ...rest, kept: true });
    used += rest.tokens;
  }

  const output = render({ files: kept, tree: treeText, format, root: options.root });
  return {
    files: kept,
    dropped,
    tree: treeText,
    tokens: estimateTokens(output),
    secrets,
    redactedCount,
    output,
  };
}

function render(input: {
  files: PackedFile[];
  tree: string;
  format: OutputFormat;
  root: string;
}): string {
  if (input.format === "json") {
    return JSON.stringify(
      {
        generator: "ctxpack",
        author: "KodYazicam",
        root: input.root,
        tree: input.tree,
        files: input.files.map(({ path, tokens, size, truncated, content }) => ({
          path,
          tokens,
          size,
          truncated,
          content,
        })),
      },
      null,
      2,
    );
  }
  if (input.format === "xml") {
    const files = input.files
      .map(
        (f) =>
          `<file path="${escapeXml(f.path)}" tokens="${f.tokens}">\n${escapeXml(f.content)}\n</file>`,
      )
      .join("\n");
    const tree = input.tree
      ? `<tree>\n${escapeXml(input.tree)}\n</tree>\n`
      : "";
    return `<context generator="ctxpack" author="KodYazicam">\n${tree}${files}\n</context>\n`;
  }
  const parts: string[] = [
    `# Context pack`,
    ``,
    `Generated by [ctxpack](https://github.com/KodYazicam/ctxpack) — KodYazicam.`,
    ``,
  ];
  if (input.tree) {
    parts.push(`## Repository tree`, ``, "```", input.tree, "```", ``);
  }
  for (const file of input.files) {
    const lang = langFromPath(file.path);
    parts.push(`## ${file.path}`, ``, `\`\`\`${lang}`, file.content.replace(/\s+$/, ""), "```", ``);
  }
  return parts.join("\n");
}

function langFromPath(path: string): string {
  const ext = path.split(".").pop()?.toLowerCase() ?? "";
  const map: Record<string, string> = {
    ts: "ts",
    tsx: "tsx",
    js: "js",
    jsx: "jsx",
    py: "python",
    rs: "rust",
    go: "go",
    json: "json",
    md: "md",
    yml: "yaml",
    yaml: "yaml",
    toml: "toml",
    sh: "bash",
    css: "css",
    html: "html",
    sql: "sql",
  };
  return map[ext] ?? "";
}

function escapeXml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}
